services:
  oradarlidar:
    image: ghcr.io/screamlab/wildbot_base_image:latest
    env_file:
      - .env
    devices:
      - "/dev/oradar:/dev/oradar"
    volumes:
      - ./launch:/workspace/launch:ro
    networks:
      - my_bridge_network
    command: "ros2 launch /workspace/launch/oradarlidar.launch.py"

networks:
  my_bridge_network:
    driver: bridge
