services:
  odom_tf_bridge:
    image: wildbot_workspace
    env_file:
      - .env
    volumes:
      - ./demo:/workspace/demo:ro
    networks:
      - my_bridge_network
    command: "python3 /workspace/demo/odom_tf_bridge.py"

networks:
  my_bridge_network:
    driver: bridge
