services:
  map_saver:
    image: wildbot_workspace
    env_file:
      - .env
    volumes:
      - ../../maps/map01:/map
    networks:
      - my_bridge_network
    command: "ros2 run nav2_map_server map_saver_cli -f /map/map01"

networks:
  my_bridge_network:
    driver: bridge
