services:
  localization:
    image: wildbot_workspace
    env_file:
      - .env
    volumes:
      - ./demo:/workspace/demo:ro
      - ../../maps:/workspace/maps:ro
    networks:
      - my_bridge_network
    command: "ros2 launch /workspace/demo/localization_wildbot.xml"

networks:
  my_bridge_network:
    driver: bridge
