services:
  dabai:
    image: ghcr.io/screamlab/wildbot_base_image:latest
    env_file:
      - .env
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    networks:
      - my_bridge_network
    command:
    - ros2
    - launch
    - orbbec_camera
    - gemini_ew.launch.py    
    - color_width:=640
    - color_height:=480
    - color_fps:=15
    - depth_width:=1280
    - depth_height:=800
    - depth_fps:=30

  compress:
    image: ghcr.io/screamlab/wildbot_base_image:latest
    env_file:
      - .env
    networks:
      - my_bridge_network
    depends_on:
      - dabai
    command: "ros2 run image_transport republish raw compressed --ros-args --remap in:=camera/color/image_raw --remap out:=camera/color/image_raw -p out.compressed.jpeg_quality:=50"

networks:
  my_bridge_network:
    driver: bridge
