services:
  slam:
    image: wildbot_workspace
    env_file:
      - .env
    volumes:
      - ./demo:/workspace/demo:ro
      - ../../maps/map01:/workspace/maps/map01
    networks:
      - my_bridge_network
    command: "ros2 launch /workspace/demo/slam_wildbot.xml"

networks:
  my_bridge_network:
    driver: bridge
