services:
  cmd_vel_relay:
    image: ghcr.io/screamlab/wildbot_base_image:latest
    env_file:
      - .env
    volumes:
      - ./demo:/workspace/demo:ro
    networks:
      - my_bridge_network
    command: "python3 /workspace/demo/cmd_vel_relay.py"

networks:
  my_bridge_network:
    driver: bridge
